kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
  - role: worker
    extraMounts:
      - hostPath: /dev
        containerPath: /dev
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: /run/lvm
        containerPath: /run/lvm
      - hostPath: /run/lock
        containerPath: /run/lock
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
